### ISSUE TITLE
PHP 8.x Fatal Error - customers view

### ISSUE THREAD

**Issue by ipajen** [motopress/mp-restaurant-menu#5]
Restaurant Menu: 2.4.2
WordPress Version: 6.2-RC4
PHP Version: 8.2.0

When going to /wp-admin/edit.php?post_type=mp_menu_item&page=mprm-customers it gives a fatal PHP error

`[23-Mar-2023 18:54:05 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\classes\models\shop\reports\customer-report-class.php:182
Stack trace:
#0 C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\classes\models\shop\reports\customer-report-class.php(182): count(false)
#1 C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\admin\customers\index.php(4): mp_restaurant_menu\classes\models\Customer_Reports->prepare_items()
#2 C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\classes\class-view.php(70): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\classes\controllers\class-controller-customer.php(153): mp_restaurant_menu\classes\View->render_html('../admin/custom...')
#4 C:\xampp\htdocs\test\wp-includes\class-wp-hook.php(308): mp_restaurant_menu\classes\controllers\Controller_customer->action_content('')
#5 C:\xampp\htdocs\test\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 C:\xampp\htdocs\test\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 C:\xampp\htdocs\test\wp-admin\admin.php(259): do_action('restaurant-menu...')
#8 C:\xampp\htdocs\test\wp-admin\edit.php(10): require_once('C:\\xampp\\htdocs...')
#9 {main}
  thrown in C:\xampp\htdocs\test\wp-content\plugins\mp-restaurant-menu\classes\models\shop\reports\customer-report-class.php on line 182`

**Comment by mototeam** [comment]
Thank you for reporting this issue. It's fixed in [this commit](https://github.com/motopress/mp-restaurant-menu/commit/93a95fd565aafa4a2c944f185ce643c466721a83#diff-724658404e362bd5b0be9465e52cfd8aee368406ecdf62726f68fcdd4be46702R182).
